### ISSUE TITLE
Import Error no module named forms

### ISSUE THREAD

**Issue by arpit1997** [nyergler/effective-django-tutorial#8]
I got this error while loading admin page at 127.0.0.1:8000/admin
` ` `
ImportError at /admin/
No module named 'forms'
Request Method: GET
Request URL:    http://127.0.0.1:8000/admin/
Django Version: 1.5.1
Exception Type: ImportError
Exception Value:  
No module named 'forms'
Exception Location: /home/arpit/Desktop/helloworld/effective-django-tutorial/contacts/views.py in <module>, line 14
Python Executable:  /usr/bin/python3
Python Version: 3.4.3
Python Path:  
['/home/arpit/Desktop/helloworld/effective-django-tutorial',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/home/arpit/.local/lib/python3.4/site-packages',
 '/usr/local/lib/python3.4/dist-packages',
 '/home/arpit/src/facebook-sdk',
 '/usr/local/lib/python3.4/dist-packages/git_remote_dropbox-0.2.2-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/PyGithub-1.28-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/pyarp-0.1.1-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/netifaces-0.10.5-py3.4-linux-x86_64.egg',
 '/usr/local/lib/python3.4/dist-packages/django_annoying-0.10.3-py3.4.egg',
 '/usr/lib/python3/dist-packages']
Server time:    Tue, 25 Oct 2016 14:43:16 -0500

forms.py is in same directory with views.py but still i am getting this error

` ` `

**Comment by nyergler** [comment]
Python 3 doesn't support implicit relative imports, which is what that import statement is.

In Python 2 you could say `import forms` and Python would look in the current module first (the implicitly relative import), and then start looking at the top level.

In Python 3, all imports are absolute (starting from the top level) unless you make them explicitly relative. So you could do:

```
from . import forms # explicitly relative
from contacts import forms # absolute 
import contacts.forms as forms # also absolute
```

**Comment by mahalakshmigangula** [comment]
ImportError: attempted relative import with no known parent package
i got this error while impoting a class relatively, what to do
